// The subheadings (textbook sections) of every chapter, keyed by "book|chapter number".
// Each subheading has its own reviews and schedule. [title, 1] marks an A-level-only section.
export const SYLLABUS = {
  "Maths Y1 (red)|1": ["Mathematical structures and arguments", "Inequality notation", "Disproof by counter example", "Proof by deduction", "Proof by exhaustion"],
  "Maths Y1 (red)|2": ["Using the laws of indices", "Working with surds"],
  "Maths Y1 (red)|3": ["Review of quadratic equations", "Graphs of quadratic functions", "Completing the square", "Quadratic inequalities", "The discriminant", "Disguised quadratics"],
  "Maths Y1 (red)|4": ["Working with polynomials", "Polynomial division", "The factor theorem", "Sketching polynomial functions"],
  "Maths Y1 (red)|5": ["Intersections of graphs", "The discriminant revisited", "Transforming graphs", "Graphs of a/x and a/x²", "Direct and inverse proportion", "Sketching inequalities in two variables"],
  "Maths Y1 (red)|6": ["Midpoint and distance between two points", "Equation of a straight line", "Parallel and perpendicular lines", "Equation of a circle", "Solving problems with lines and circles"],
  "Maths Y1 (red)|7": ["Introducing logarithms", "Laws of logarithms", "Solving exponential equations", "Disguised quadratics"],
  "Maths Y1 (red)|8": ["Graphs of exponential functions", "Graphs of logarithms", "Exponential functions and mathematical modelling", "Fitting models to data"],
  "Maths Y1 (red)|9": ["The binomial theorem", "Calculating the binomial coefficients", "Applications of the binomial theorem"],
  "Maths Y1 (red)|10": ["Definitions and graphs of the sine and cosine functions", "Definition and graph of the tangent function", "Exact values of trigonometric functions", "Trigonometric identities", "Introducing trigonometric equations", "Transformations of trigonometric graphs", "More complex trigonometric equations"],
  "Maths Y1 (red)|11": ["The sine rule", "The cosine rule", "Area of a triangle"],
  "Maths Y1 (red)|12": ["Describing vectors", "Operations with vectors", "Position and displacement vectors", "Using vectors to solve geometrical problems"],
  "Maths Y1 (red)|13": ["Sketching derivatives", "Differentiation from first principles", "Rules of differentiation", "Simplifying into terms of the form axⁿ", "Interpreting derivatives and second derivatives"],
  "Maths Y1 (red)|14": ["Tangents and normals", "Stationary points", "Optimisation"],
  "Maths Y1 (red)|15": ["Rules for integration", "Simplifying into terms of the form axⁿ", "Finding the equation of a curve", "Definite integration", "Geometrical significance of definite integration"],
  "Maths Y1 (red)|16": ["A reminder of statistical diagrams", "Standard deviation", "Calculations from frequency tables", "Scatter diagrams and correlation", "Outliers and cleaning data"],
  "Maths Y1 (red)|17": ["Combining probabilities", "Probability distributions", "The binomial distribution"],
  "Maths Y1 (red)|18": ["Populations and samples", "Introduction to hypothesis testing", "Critical region for a hypothesis test"],
  "Maths Y1 (red)|19": ["Mathematical models in mechanics", "Displacement, velocity and acceleration", "Kinematics and calculus", "Using travel graphs", "Solving problems in kinematics"],
  "Maths Y1 (red)|20": ["Deriving the constant acceleration formulae", "Using the constant acceleration formulae", "Vertical motion under gravity", "Multi-stage problems"],
  "Maths Y1 (red)|21": ["Newton's laws of motion", "Combining forces", "Types of forces", "Gravity and weight", "Forces in equilibrium"],
  "Maths Y1 (red)|22": ["Newton's third law", "Normal reaction force", "Further equilibrium problems", "Connected particles", "Pulleys"],
  "Maths Y2 (green)|1": ["A reminder of methods of proof", "Proof by contradiction", "Criticising proofs"],
  "Maths Y2 (green)|2": ["Mappings and functions", "Domain and range", "Composite functions", "Inverse functions"],
  "Maths Y2 (green)|3": ["Combined transformations", "Modulus function", "Modulus equations and inequalities"],
  "Maths Y2 (green)|4": ["General sequences", "General series and sigma notation", "Arithmetic sequences", "Arithmetic series", "Geometric sequences", "Geometric series", "Infinite geometric series", "Using sequences and series to solve problems"],
  "Maths Y2 (green)|5": ["Review of the factor theorem", "Simplifying rational expressions", "Partial fractions with distinct factors", "Partial fractions with a repeated factor"],
  "Maths Y2 (green)|6": ["General binomial expansion", "Binomial expansions of compound expressions"],
  "Maths Y2 (green)|7": ["Introducing radian measure", "Inverse trigonometric functions and solving trigonometric equations", "Modelling with trigonometric functions", "Arcs and sectors", "Triangles and circles", "Small angle approximations"],
  "Maths Y2 (green)|8": ["Compound angle identities", "Double angle identities", "Expressions of the form a sin x + b cos x", "Reciprocal trigonometric functions"],
  "Maths Y2 (green)|9": ["Differentiation", "Integration"],
  "Maths Y2 (green)|10": ["The chain rule", "The product rule", "The quotient rule", "Implicit differentiation", "Differentiating inverse functions"],
  "Maths Y2 (green)|11": ["Reversing standard derivatives", "Integration by substitution", "Integration by parts", "Using trigonometric identities in integration", "Integrating rational functions"],
  "Maths Y2 (green)|12": ["Properties of curves", "Parametric equations", "Related rates of change", "More complicated areas"],
  "Maths Y2 (green)|13": ["Introduction to differential equations", "Separable differential equations", "Modelling with differential equations"],
  "Maths Y2 (green)|14": ["Locating roots of a function", "The Newton–Raphson method", "Limitations of the Newton–Raphson method", "Fixed-point iteration", "Limitations of fixed-point iteration; alternative rearrangements"],
  "Maths Y2 (green)|15": ["Integration as the limit of a sum", "The trapezium rule"],
  "Maths Y2 (green)|16": ["Set notation and Venn diagrams", "Two-way tables", "Tree diagrams", "Modelling with probability"],
  "Maths Y2 (green)|17": ["Introduction to normal probabilities", "Inverse normal distribution", "Finding unknown μ or σ", "Modelling with the normal distribution"],
  "Maths Y2 (green)|18": ["Distribution of the sample mean", "Hypothesis tests for a mean", "Hypothesis tests for correlation coefficients"],
  "Maths Y2 (green)|19": ["Describing motion in two dimensions", "Constant acceleration equations", "Calculus with vectors", "Vectors in three dimensions", "Solving geometrical problems"],
  "Maths Y2 (green)|20": ["Modelling projectile motion", "The trajectory of a projectile"],
  "Maths Y2 (green)|21": ["Resolving forces", "Coefficient of friction", "Motion on a slope", "Further equilibrium problems"],
  "Maths Y2 (green)|22": ["The turning effect of a force", "Equilibrium", "Non-uniform rods", "Further equilibrium problems"],
  "Further Pure Core 1 (blue)|1": ["Addition, subtraction and scalar multiplication of matrices", "Matrix multiplication", "Determinants and inverses of 2×2 matrices", "Determinants and inverses of 3×3 matrices"],
  "Further Pure Core 1 (blue)|2": ["Vector equation of a line", "Cartesian equation of a line", "Intersections of lines", "Angles and the scalar product", "The vector product"],
  "Further Pure Core 1 (blue)|3": ["Linear simultaneous equations", "Matrices as linear transformations", "Further transformations in 2-D", "Invariant points and invariant lines", "Transformations in 3-D"],
  "Further Pure Core 1 (blue)|4": ["Definition and basic arithmetic of i", "Division and complex conjugates", "Geometric representation", "Modulus and argument", "Loci in the complex plane", "Operations in modulus–argument form"],
  "Further Pure Core 1 (blue)|5": ["Factorising polynomials", "Complex solutions to polynomial equations", "Roots and coefficients", "Finding an equation with given roots", "Transforming equations"],
  "Further Pure Core 1 (blue)|6": ["The principle of mathematical induction", "Induction and matrices", "Induction and divisibility", "Induction and inequalities"],
  "Further Pure Core 2|1": ["Review of proof by induction", "Induction and series", "Using standard series", "The method of differences"],
  "Further Pure Core 2|2": ["De Moivre's theorem", "Complex exponents", "Roots of complex numbers", "Roots of unity", "Further factorising", "Geometry of complex numbers"],
  "Further Pure Core 2|3": ["Deriving multiple angle formulae", "Application to polynomial equations", "Powers of trigonometric functions", "Trigonometric series"],
  "Further Pure Core 2|4": ["Equation of a plane", "Intersection between a line and a plane", "Angles between lines and planes", "Distances between points, lines and planes"],
  "Further Pure Core 2|5": ["Linear simultaneous equations", "Intersections of planes"],
  "Further Pure Core 2|6": ["Defining hyperbolic functions", "Inverse hyperbolic functions", "Hyperbolic identities", "Solving harder hyperbolic equations", "Differentiation", "Integration"],
  "Further Pure Core 2|7": ["Differentiation of inverse trigonometric functions", "Differentiation of inverse hyperbolic functions", "Using inverse trigonometric and hyperbolic functions in integration", "Using partial fractions in integration"],
  "Further Pure Core 2|8": ["Maclaurin series", "Using standard Maclaurin series", "Improper integrals", "Volumes of revolution", "Mean value of a function"],
  "Further Pure Core 2|9": ["Curves in polar coordinates", "Some features of polar curves", "Changing between polar and Cartesian coordinates", "Area enclosed by a polar curve", "Area between two curves"],
  "Further Pure Core 2|10": ["Terminology of differential equations", "The integrating factor method for first order equations", "Homogeneous second order linear differential equations with constant coefficients", "Non-homogeneous second order linear differential equations with constant coefficients"],
  "Further Pure Core 2|11": ["Forming differential equations", "Simple harmonic motion", "Damping and damped oscillations", "Linear systems"],
  "Further Stats|1": ["The product principle and the addition principle", "Permutations", "Combinations", "The exclusion principle", "Selections where order matters", "Keeping objects together or separated", "Permuting objects with repetitions", "Counting principles in probability"],
  "Further Stats|2": ["Average and spread of a discrete random variable", "Expectation and variance of transformations of discrete random variables", "The discrete uniform distribution", "Binomial distribution", "The geometric distribution"],
  "Further Stats|3": ["Using the Poisson model"],
  "Further Stats|4": ["The single-sample sign test", "The single-sample Wilcoxon signed-rank test", "Matched-pairs (or paired-sample) tests", "Wilcoxon rank-sum test", "Normal approximations"],
  "Further Stats|5": ["Pearson's product moment correlation coefficient", "Spearman's rank correlation coefficient", "Linear regression"],
  "Further Stats|6": ["Contingency tables", "Yates' correction", "Goodness-of-fit tests"],
  "Further Stats|7": ["Continuous random variables", "Averages and measures of spread of continuous random variables", "Expectation and variance of functions of a random variable", "Cumulative distribution functions", "Piecewise-defined probability density functions", "Continuous uniform distribution", "Exponential distribution", "Distributions of functions of a continuous random variable", "Goodness-of-fit test with continuous distributions"],
  "Further Stats|8": ["Adding independent random variables", "Expectation and variance of the sample mean", "Unbiased estimates of the mean and the variance", "Linear combinations of normal variables", "The distribution of means of large samples"],
  "Further Stats|9": ["Hypothesis testing for the mean of a large sample", "Confidence intervals"],
  "Further Mechanics|1": ["The work done by a force", "Kinetic energy and the work–energy principle", "Potential energy, mechanical energy and conservation of mechanical energy", "Work done by a force at an angle to the direction of motion", "Power"],
  "Further Mechanics|2": ["Defining and calculating dimensions", "Units and dimensions of sums, differences and angles", "Finding dimensions from units and derivatives and predicting formulae", "Summary of dimensions and units"],
  "Further Mechanics|3": ["Momentum and impulse", "Collisions and the principle of conservation of momentum", "Restitution, kinetic energy and impulsive tension"],
  "Further Mechanics|4": ["Linear speed vs angular speed", "Acceleration in horizontal circular motion", "Solving problems involving motion in a horizontal circle"],
  "Further Mechanics|5": ["Centre of mass of a system of point masses", "Centres of mass of standard shapes", "Centres of mass of composite bodies"],
  "Further Mechanics|6": ["Work done by a variable force f(x)", "Hooke's law, work done against elasticity and elastic potential energy", "Problem solving involving work, energy and power", "Using vectors to calculate work done, kinetic energy and power"],
  "Further Mechanics|7": ["Working with acceleration, velocity and displacement", "Variable force"],
  "Further Mechanics|8": ["Variable force and vector notation", "Oblique impacts and the impulse–momentum triangle", "Oblique collisions of two spheres and impulsive tensions in strings"],
  "Further Mechanics|9": ["Conservation of mechanical energy", ["Components of acceleration (a general model)", 1], ["Problem solving situations", 1]],
  "Further Mechanics|10": ["Centres of mass by integration", "Equilibrium of a rigid body"],
};
